"""Export the governed metric catalogue for the product surfaces.

The metrics route shows real definitions, not fixtures. They are the same YAML
files dbt, Cube and the API compile from, loaded through the same
`MetricRegistry` that validates them — so a metric that would fail validation
never reaches the page, and `is_certified` on the page is the computed property
rather than a flag somebody set.

Only what a product surface may show is exported. `measure_expression` is
deliberately absent: it is the formula, `metric.view_query_detail` gates it, and
a catalogue baked into a client bundle cannot enforce a capability. Shipping it
here would put the SQL in every visitor's browser regardless of role.

Run: `uv run python services/api/tools/export_metric_catalogue.py`
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from metrics.contract import MetricRegistry

CATALOGUE_PATH = (
    Path(__file__).resolve().parents[3] / "packages" / "contracts" / "src" / "metric-catalogue.json"
)


def build() -> dict[str, Any]:
    registry = MetricRegistry.load()
    return {
        "$comment": (
            "GENERATED by services/api/tools/export_metric_catalogue.py — do not edit. "
            "Source: data/metrics/definitions/*.yml. "
            "measure_expression is withheld on purpose: it is gated by "
            "metric.view_query_detail and a client bundle cannot enforce that."
        ),
        "metrics": [
            {
                "key": definition.key,
                "name": definition.name,
                "description": definition.description.strip(),
                "owner": definition.owner,
                "version": definition.version,
                "identity": definition.identity,
                "unit": definition.unit.value,
                "grain": list(definition.grain),
                "dimensions": list(definition.dimensions),
                "sourceModels": list(definition.source_models),
                "sensitivity": definition.sensitivity.value,
                "qualityTests": [test.value for test in definition.quality_tests],
                "exampleCount": len(definition.examples),
                # Computed, never set. Certification follows from having an
                # owner, executable examples and quality tests.
                "isCertified": definition.is_certified,
                "certificationGaps": definition.certification_gaps,
                "validFrom": definition.valid_from.isoformat(),
                "validTo": definition.valid_to.isoformat() if definition.valid_to else None,
                "isExposureBearing": definition.is_exposure_bearing,
            }
            for definition in sorted(registry.definitions, key=lambda d: d.key)
        ],
    }


def main() -> None:
    CATALOGUE_PATH.write_text(json.dumps(build(), indent=2, sort_keys=True) + "\n")
    print(f"wrote {CATALOGUE_PATH}")


if __name__ == "__main__":
    main()
