"""Export the gap lifecycle as a JSON contract.

The transition table is defined once, in Python, because that is where it is
enforced — the API refuses an illegal transition and the database refuses an
inconsistent row. The web app needs the same table to decide which actions to
offer, and hand-copying it into TypeScript would give two tables that agree
right up until somebody edits one.

So the Python module stays the source and this writes the artefact both sides
consume, exactly as `docs/design-tokens/tokens.json` does for colour.
`test_lifecycle_contract_matches_the_module` fails if the committed file drifts,
which is what makes the artefact trustworthy rather than merely present.

Run: `uv run python services/api/tools/export_gap_lifecycle.py`
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fitos_api.gaps.lifecycle import (
    DISMISSAL_REASONS,
    TERMINAL,
    TRANSITION_CAPABILITY,
    TRANSITIONS,
    GapStatus,
)

CONTRACT_PATH = (
    Path(__file__).resolve().parents[3] / "packages" / "contracts" / "src" / "gap-lifecycle.json"
)


def build() -> dict[str, Any]:
    return {
        "$comment": (
            "GENERATED by services/api/tools/export_gap_lifecycle.py — do not edit. "
            "Source: services/api/src/fitos_api/gaps/lifecycle.py. "
            "test_lifecycle_contract_matches_the_module fails if this drifts."
        ),
        "statuses": [status.value for status in GapStatus],
        "terminal": sorted(status.value for status in TERMINAL),
        # Sorted so the artefact is stable across runs: a set iterated in
        # whatever order Python felt like would produce a diff on every export.
        "transitions": {
            source.value: sorted(target.value for target in targets)
            for source, targets in TRANSITIONS.items()
        },
        "transitionCapability": {
            status.value: capability.value for status, capability in TRANSITION_CAPABILITY.items()
        },
        "dismissalReasons": list(DISMISSAL_REASONS),
    }


def main() -> None:
    CONTRACT_PATH.write_text(json.dumps(build(), indent=2, sort_keys=True) + "\n")
    print(f"wrote {CONTRACT_PATH}")


if __name__ == "__main__":
    main()
