#!/usr/bin/env node
// Generates dist/tokens.css from docs/design-tokens/tokens.json.
// Components consume the semantic tier only; a component referencing a
// primitive directly is a lint error (docs/design-system.md §1).
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(
  readFileSync(resolve(here, "../../../docs/design-tokens/tokens.json"), "utf8"),
);

/**
 * "neutral.400" -> "#9497A1"; "status.critical.400" -> "#FF6166"; a literal
 * "#RRGGBB" passes through.
 *
 * The status ramps are nested one level deeper than the flat scales, and the
 * two-segment version of this function silently produced `[object Object]` for
 * them rather than failing — so the throw below is not decoration.
 */
const resolveRef = (raw) => {
  if (raw.startsWith("#")) return raw;
  const value = raw.split(".").reduce((node, key) => node?.[key], tokens.primitive);
  if (typeof value !== "string") throw new Error(`unresolvable token reference: ${raw}`);
  return value;
};

const lines = [
  "/* GENERATED by packages/ui/scripts/build-tokens.mjs — do not edit.",
  "   Source: docs/design-tokens/tokens.json */",
  "",
];

// Tier 1 — primitives.
lines.push(":root {");
for (const [scale, steps] of Object.entries(tokens.primitive)) {
  for (const [step, value] of Object.entries(steps)) {
    if (typeof value === "string") {
      lines.push(`  --${scale}-${step}: ${value};`);
    } else {
      for (const [sub, v] of Object.entries(value))
        lines.push(`  --${scale}-${step}-${sub}: ${v};`);
    }
  }
}
lines.push("}", "");

// Tier 2 — semantic, per theme. Dark is the default; light is opt-in via
// [data-theme="light"] and prefers-color-scheme.
const emitSemantic = (theme, indent) =>
  Object.entries(tokens.semantic[theme])
    .filter(([key]) => !key.startsWith("$"))
    .map(([key, raw]) => `${indent}--${key}: ${resolveRef(raw)};`);

lines.push(":root,", '[data-theme="dark"] {', ...emitSemantic("dark", "  "), "}", "");
lines.push('[data-theme="light"] {', ...emitSemantic("light", "  "), "}", "");
lines.push(
  "@media (prefers-color-scheme: light) {",
  '  :root:not([data-theme="dark"]) {',
  ...emitSemantic("light", "    "),
  "  }",
  "}",
  "",
);

const out = resolve(here, "../dist/tokens.css");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n"));
console.log(`wrote ${out} (${lines.length} lines)`);
