"use client";

import { useMemo, useState } from "react";
import { SiteShell, Status } from "./FitOSApp";
import { defaultRetailerConfig, capacityFromQueue, rankFulfilment, type FulfilmentInput, type Method, type RetailerConfig } from "./fulfilment-engine";
import { useScenario } from "./scenario-context";

const allMethods: Method[] = ["Staff delivery now", "Companion collection", "Customer self-collection", "Batch pick", "Bring before I finish", "Collect at checkout", "Reserve nearby", "Home delivery", "Alternative product"];
const scenarioInputs: Record<string, Omit<FulfilmentInput, "capacity">> = {
  "Quiet Store": { activeAssociates: 4, queueLength: 2, companionPresent: false, location: "Shop floor", stockConfidence: "Confirmed", stockUnits: 6, walkingMinutes: 2, timingPreference: "As soon as possible", accessibilityNeed: false, batchOpportunity: false, onlineAvailable: true, nearbyStoreAvailable: true },
  "Busy Saturday": { activeAssociates: 2, queueLength: 8, companionPresent: true, location: "Stockroom", stockConfidence: "Confirmed", stockUnits: 6, walkingMinutes: 4, timingPreference: "Before I finish", accessibilityNeed: false, batchOpportunity: true, onlineAvailable: true, nearbyStoreAvailable: true },
  "Stock Discrepancy": { activeAssociates: 2, queueLength: 7, companionPresent: false, location: "Stockroom", stockConfidence: "Check", stockUnits: 2, walkingMinutes: 5, timingPreference: "As soon as possible", accessibilityNeed: false, batchOpportunity: true, onlineAvailable: true, nearbyStoreAvailable: true },
  "Batch Pick": { activeAssociates: 2, queueLength: 7, companionPresent: false, location: "Stockroom", stockConfidence: "Confirmed", stockUnits: 8, walkingMinutes: 5, timingPreference: "No rush", accessibilityNeed: false, batchOpportunity: true, onlineAvailable: false, nearbyStoreAvailable: false },
  "Companion Collection": { activeAssociates: 2, queueLength: 9, companionPresent: true, location: "Shop floor", stockConfidence: "Confirmed", stockUnits: 4, walkingMinutes: 3, timingPreference: "As soon as possible", accessibilityNeed: false, batchOpportunity: false, onlineAvailable: true, nearbyStoreAvailable: false },
};

export function FulfilmentExperience() {
  const { scenario } = useScenario();
  const [config, setConfig] = useState<RetailerConfig>(defaultRetailerConfig);
  const [request, setRequest] = useState<FulfilmentInput>(() => ({ ...scenarioInputs[scenario], capacity: capacityFromQueue(scenarioInputs[scenario].queueLength, defaultRetailerConfig) }));
  const [lastScenario, setLastScenario] = useState(scenario);
  if (scenario !== lastScenario) { const next = scenarioInputs[scenario]; setLastScenario(scenario); setRequest({ ...next, capacity: capacityFromQueue(next.queueLength, config) }); }
  const options = useMemo(() => rankFulfilment({ ...request, capacity: capacityFromQueue(request.queueLength, config) }, config), [request, config]);
  const capacity = capacityFromQueue(request.queueLength, config);
  const update = <K extends keyof FulfilmentInput>(key: K, value: FulfilmentInput[K]) => setRequest(current => ({ ...current, [key]: value }));
  const toggleMethod = (method: Method) => setConfig(current => ({ ...current, enabledMethods: current.enabledMethods.includes(method) ? current.enabledMethods.filter(item => item !== method) : [...current.enabledMethods, method] }));
  return <SiteShell><section className="fulfilment-page"><div className="fulfilment-intro"><div><p className="eyebrow">Adaptive fulfilment · deterministic rules</p><h1>Choose the best next route, and show why.</h1><p>FitOS ranks enabled fulfilment options from clear operational inputs. The explanation stays focused on the customer and request, without revealing sensitive staffing details.</p></div><div className={`capacity-hero ${capacity.toLowerCase()}`}><span>Live capacity</span><b>{capacity}</b><p>{capacity === "Green" ? "Immediate staff delivery is available." : capacity === "Amber" ? "Estimates, batching and companion routes are promoted." : "Immediate delivery is limited; protected needs stay prioritised."}</p></div></div>
    <section className="fulfilment-workbench"><div className="request-inputs"><div className="section-heading"><div><p className="eyebrow">Request context</p><h2>Inputs</h2></div><Status tone={capacity === "Green" ? "good" : "warn"}>{scenario}</Status></div><div className="input-grid"><label>Queue length<input type="range" min="0" max="14" value={request.queueLength} onChange={event => update("queueLength", Number(event.target.value))} /><b>{request.queueLength} requests</b></label><label>Stock confidence<select value={request.stockConfidence} onChange={event => update("stockConfidence", event.target.value as FulfilmentInput["stockConfidence"])}><option>Confirmed</option><option>Likely</option><option>Check</option></select></label><label>Product location<select value={request.location} onChange={event => update("location", event.target.value as FulfilmentInput["location"])}><option>Shop floor</option><option>Stockroom</option></select></label><label>Customer timing<select value={request.timingPreference} onChange={event => update("timingPreference", event.target.value as FulfilmentInput["timingPreference"])}><option>As soon as possible</option><option>Before I finish</option><option>No rush</option></select></label><label>Walking time<input type="range" min="1" max="9" value={request.walkingMinutes} onChange={event => update("walkingMinutes", Number(event.target.value))} /><b>{request.walkingMinutes} min</b></label><label>Stock units<input type="number" min="0" max="20" value={request.stockUnits} onChange={event => update("stockUnits", Number(event.target.value))} /></label></div><div className="switches"><button className={request.companionPresent ? "on" : ""} onClick={() => update("companionPresent", !request.companionPresent)}><i />Companion present</button><button className={request.batchOpportunity ? "on" : ""} onClick={() => update("batchOpportunity", !request.batchOpportunity)}><i />Batch opportunity</button><button className={request.accessibilityNeed ? "on" : ""} onClick={() => update("accessibilityNeed", !request.accessibilityNeed)}><i />Accessibility need</button><button className={request.nearbyStoreAvailable ? "on" : ""} onClick={() => update("nearbyStoreAvailable", !request.nearbyStoreAvailable)}><i />Nearby-store option</button><button className={request.onlineAvailable ? "on" : ""} onClick={() => update("onlineAvailable", !request.onlineAvailable)}><i />Home-delivery option</button></div></div>
      <div className="ranked-options"><div className="section-heading"><div><p className="eyebrow">Ranked output</p><h2>Available routes</h2></div><span>{options.length} options</span></div><div className="ranked-list">{options.map((option, index) => <article className={index === 0 ? "top" : ""} key={option.method}><div className="rank-number">{String(index + 1).padStart(2, "0")}</div><div><div className="option-title"><h3>{option.method}</h3>{index === 0 && <Status tone="good">Recommended</Status>}</div><p>{option.explanation}</p></div><span>{option.estimate}</span></article>)}</div><div className="why-card"><p className="eyebrow">Why this option?</p><h3>{options[0].method}</h3><p>{options[0].explanation} It ranks first under the current retailer policy and live request conditions.</p></div></div></section>
    <section className="policy-section"><div className="policy-copy"><p className="eyebrow">Retailer configuration</p><h2>Set the operating rules once.</h2><p>Retailers decide which routes are enabled, where capacity changes state, how long a batch window lasts and how cautious the stock-confidence threshold should be.</p><button className="text-button" onClick={() => setConfig(defaultRetailerConfig)}>Restore example policy ↺</button></div><div className="policy-controls"><div className="policy-pairs"><label>Amber at queue<input type="number" min="1" max="12" value={config.queueThresholds.amber} onChange={event => setConfig(current => ({ ...current, queueThresholds: { ...current.queueThresholds, amber: Number(event.target.value) } }))} /></label><label>Red at queue<input type="number" min="2" max="15" value={config.queueThresholds.red} onChange={event => setConfig(current => ({ ...current, queueThresholds: { ...current.queueThresholds, red: Number(event.target.value) } }))} /></label><label>Batch window<input type="number" min="1" max="20" value={config.batchWindowMinutes} onChange={event => setConfig(current => ({ ...current, batchWindowMinutes: Number(event.target.value) }))} /><small>minutes</small></label><label>Maximum promise<input type="number" min="3" max="30" value={config.maximumPromiseMinutes} onChange={event => setConfig(current => ({ ...current, maximumPromiseMinutes: Number(event.target.value) }))} /><small>minutes</small></label><label>Minimum confidence<select value={config.minimumStockConfidence} onChange={event => setConfig(current => ({ ...current, minimumStockConfidence: event.target.value as RetailerConfig["minimumStockConfidence"] }))}><option>Confirmed</option><option>Likely</option><option>Check</option></select></label></div><div className="method-toggles"><span>Enabled methods</span>{allMethods.map(method => <button className={config.enabledMethods.includes(method) ? "enabled" : ""} onClick={() => toggleMethod(method)} key={method}><i>{config.enabledMethods.includes(method) ? "✓" : ""}</i>{method}</button>)}</div></div></section>
    <section className="capacity-explainer"><article className="green"><span>Green</span><h3>Immediate delivery</h3><p>Staff delivery now is ranked strongly where a confirmed route is available.</p></article><article className="amber"><span>Amber</span><h3>Plan the hand-off</h3><p>Estimates, batching and companion collection move up the list.</p></article><article className="red"><span>Red</span><h3>Protect the floor</h3><p>Delayed routes and alternatives are prioritised, while accessibility needs remain protected.</p></article></section>
  </section></SiteShell>;
}
