"use client";

import Link from "next/link";
import { SiteShell, Status } from "./FitOSApp";
import { products, rooms } from "./data";

function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
function ArrowLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link className="text-link" href={href}>{children} <span>→</span></Link>; }

export function MarketingHome() {
  return <SiteShell>
    <section className="marketing-hero">
      <div className="marketing-hero-copy"><Eyebrow>Fitting-room operations</Eyebrow><h1>Turn fitting-room intent into fulfilled sales.</h1><p>FitOS gives store teams one shared view of product requests, availability and workload—so customers can keep moving when they are ready to decide.</p><div className="hero-actions"><Link className="button" href="/demo/customer">Explore the demo <span>→</span></Link><ArrowLink href="/platform">See how FitOS works</ArrowLink></div><div className="hero-signal"><i /><span>Built around existing garment barcodes and store devices</span></div></div>
      <div className="intent-visual"><div className="intent-top"><span>FITOS / FLOOR 1</span><Status tone="good">Live operations</Status></div><div className="intent-card"><div><p>Fitting room request</p><strong>Room 05</strong></div><b>2 min</b><h3>Textured Overshirt</h3><span>M · Olive · 6 located</span><div className="intent-route"><em>Floor B · Rail 12</em><i /><em>Room 05</em></div></div><div className="intent-rooms">{rooms.slice(0, 24).map(room => <i className={room.state.toLowerCase()} key={room.id} />)}</div><p>One live queue connects the room, product and team.</p></div>
    </section>

    <section className="problem-section"><div><Eyebrow>The moment that matters</Eyebrow><h2>High purchase intent already exists in the fitting room.</h2></div><p>Customers are comparing fit, colour and the rest of an outfit. The store has a valuable signal—but it often arrives as a hurried question, a handwritten list or a missed moment.</p></section>
    <section className="manual-workflow"><div className="workflow-title"><Eyebrow>Today&apos;s manual workflow</Eyebrow><h2>Each request creates a little more uncertainty.</h2></div><div className="workflow-steps"><article><span>01</span><h3>A customer asks</h3><p>“Do you have this in another size?” becomes a search for product context.</p></article><article><span>02</span><h3>A colleague leaves</h3><p>The floor loses coverage while they check rails, stockroom and colleagues.</p></article><article><span>03</span><h3>The room waits</h3><p>Requests and availability are hard to coordinate across the whole fitting-room bank.</p></article><article><span>04</span><h3>Demand disappears</h3><p>Unfulfilled requests are rarely captured as a useful signal for the store.</p></article></div></section>

    <section className="rooms-one-colleague"><div className="rooms-copy"><Eyebrow>Capacity is finite</Eyebrow><h2>32 rooms. One colleague. A queue that keeps changing.</h2><p>A button can create more requests, but it does not decide which one matters next. FitOS brings room activity, product location, request age and team capacity together before it asks someone to move.</p><ArrowLink href="/demo/associate">See the associate workflow</ArrowLink></div><div className="colleague-map"><div className="map-summary"><span>Fitting rooms</span><b>32</b><Status tone="warn">12 active requests</Status></div><div className="map-grid">{rooms.map(room => <div className={room.state.toLowerCase()} key={room.id}><b>{String(room.id).padStart(2, "0")}</b><small>{room.state === "Assisted" ? "Help" : room.state}</small></div>)}</div><div className="colleague-lane"><span className="avatar">L</span><div><b>Leah K. · Fitting rooms</b><small>4 active tasks · 2 available slots</small></div><Status tone="good">Available</Status></div></div></section>

    <section className="flow-section"><div className="centre-intro"><Eyebrow>One operating flow</Eyebrow><h2>FitOS manages the request from intent to learning.</h2><p>It is not an AI stylist. It is a product-aware operations layer for the fitting room.</p></div><div className="fitos-flow"><article><span>01</span><div className="flow-icon barcode-icon">|||||</div><h3>Identify</h3><p>Scan the barcode already attached to the garment.</p></article><article><span>02</span><div className="flow-icon match-icon">+</div><h3>Recommend</h3><p>Present complements and alternatives with stock context.</p></article><article><span>03</span><div className="flow-icon route-icon">→</div><h3>Fulfil</h3><p>Route tasks to the right place and available colleague.</p></article><article><span>04</span><div className="flow-icon signal-icon">⌁</div><h3>Learn</h3><p>Keep a record of completed, delayed and missed demand.</p></article></div></section>

    <section className="recommendation-section"><div className="recommendation-copy"><Eyebrow>Stock-aware recommendation</Eyebrow><h2>Useful next products, with the confidence to act on them.</h2><p>FitOS considers product compatibility, variant availability, location and confidence. The customer sees relevant options; the team sees what can be fulfilled and from where.</p><div className="rule-list"><span><i>✓</i> Complementary products and alternatives</span><span><i>✓</i> Size, colour and location context</span><span><i>✓</i> Availability shown as confidence, not a promise</span></div></div><div className="recommendation-board"><p>Works with Textured Overshirt</p>{products.slice(0, 3).map((product, i) => <article key={product.sku}><div className={`recommendation-swatch ${product.category.toLowerCase()}`}><span>{product.category.slice(0, 2)}</span></div><div><b>{product.name}</b><small>{product.size} · {product.colour}</small></div><Status tone={i === 2 ? "warn" : "good"}>{product.stock} · {product.confidence}</Status></article>)}</div></section>

    <section className="fulfilment-section"><div className="fulfilment-heading"><Eyebrow>Adaptive fulfilment</Eyebrow><h2>Choose the delivery method that fits the floor right now.</h2><p>FitOS can favour a direct floor pick, a stockroom task, a bundled route or a graceful alternative when capacity or confidence changes.</p></div><div className="fulfilment-methods"><article><span>Floor pick</span><h3>Closest confirmed item</h3><p>Send a nearby colleague to a known floor location.</p></article><article><span>Stockroom</span><h3>Queue with context</h3><p>Group requests that share the same stockroom route.</p></article><article><span>Alternative</span><h3>Keep the customer moving</h3><p>Offer an available equivalent when the requested variant needs checking.</p></article><article><span>Collection</span><h3>Plan the hand-off</h3><p>Use a calm collection point when the room team is under pressure.</p></article></div></section>

    <section className="workload-section"><div><Eyebrow>Associate workload</Eyebrow><h2>Give each colleague a queue they can actually work.</h2><p>FitOS balances live room needs with task count, location and availability. Managers can see where cover is needed before a queue becomes hard to recover.</p><ArrowLink href="/demo/manager">Open the manager view</ArrowLink></div><div className="workload-card"><div className="workload-header"><span>Team capacity</span><b>11 / 24</b></div>{["Leah K.", "Ravi S.", "Amelia B."].map((name, i) => <div className="workload-row" key={name}><span className="avatar">{name[0]}</span><div><b>{name}</b><small>{i === 1 ? "Picking" : "Fitting rooms"}</small></div><i><em style={{ width: `${[66, 84, 35][i]}%` }} /></i><Status tone={i === 1 ? "warn" : "good"}>{[4, 5, 2][i]} active</Status></div>)}</div></section>

    <section className="analytics-section"><div className="centre-intro"><Eyebrow>Demand you can see</Eyebrow><h2>Make fitting-room activity useful beyond the room.</h2><p>FitOS connects the operational detail of each request to clear product and service signals.</p></div><div className="analytics-grid"><article><span>Customer</span><h3>What did they ask to try next?</h3><p>See product requests and recommendation engagement by fitting-room journey.</p></article><article><span>Operational</span><h3>Where does service slow down?</h3><p>Track request volume, queue age, delivery time and room capacity.</p></article><article><span>Inventory</span><h3>Which variants need attention?</h3><p>Find recurring size, colour and availability signals without making stock guarantees.</p></article><article><span>Strategic</span><h3>What should the team test next?</h3><p>Use observed demand to inform floor placement, staffing and future pilots.</p></article></div></section>

    <section className="deployment-section"><div className="deployment-device"><div className="device-screen"><span>SCAN LABEL</span><b>5061048301197</b><i>|||||||||||||||</i><small>Textured Overshirt · M · Olive</small></div></div><div><Eyebrow>Designed for the store you have</Eyebrow><h2>Existing barcode. Existing device. No new hardware requirement.</h2><p>FitOS starts with the garment labels and devices teams already use. It is a browser prototype with deterministic local data—not a production integration.</p><div className="deployment-tags"><Status tone="good">Existing barcode labels</Status><Status tone="good">Browser-based</Status><Status>RFID optional</Status></div></div></section>
    <section className="marketing-cta"><div><Eyebrow>Start with a pilot</Eyebrow><h2>Test the operating model on one floor.</h2><p>Use a focused pilot to learn what customers ask for, where the team feels pressure and which fulfilment patterns fit the store.</p></div><Link className="button" href="/pilot">Plan a pilot <span>→</span></Link></section>
  </SiteShell>;
}

export function MarketingPlatform() {
  return <SiteShell>
    <section className="platform-hero"><Eyebrow>The platform</Eyebrow><h1>Everything around the request, working as one.</h1><p>FitOS takes a small fitting-room interaction and carries its product context through recommendation, fulfilment, workload management and analysis.</p><Link className="button" href="/demo/customer">Explore the demo <span>→</span></Link></section>
    <section className="platform-index"><span>Inside FitOS</span>{["Customer experience", "Recommendation rules", "Fulfilment engine", "Associate workflow", "Analytics", "Integrations & limitations"].map((item, i) => <a href={`#platform-${i}`} key={item}>{String(i + 1).padStart(2, "0")} · {item}</a>)}</section>
    <section className="platform-detail" id="platform-0"><div><Eyebrow>Customer experience</Eyebrow><h2>Start with the garment in hand.</h2></div><p>The customer scans an existing garment label, then sees complementary products and alternatives grounded in the selected item. The experience is product-led and private; FitOS does not present itself as an AI stylist.</p><Link className="secondary-link" href="/demo/customer">View customer demo →</Link></section>
    <section className="platform-detail inverse" id="platform-1"><div><Eyebrow>Recommendation rules</Eyebrow><h2>Relevance is only helpful when it is fulfilment-aware.</h2></div><div className="detail-list"><span>Compatibility tags connect products that belong together.</span><span>Size, colour and variant data make the recommendation specific.</span><span>Location and confidence make the next action clear for the team.</span><span>Low-confidence stock leads to a check or alternative, not a guarantee.</span></div></section>
    <section className="platform-detail" id="platform-2"><div><Eyebrow>Fulfilment engine</Eyebrow><h2>Adapt to the work that is already happening.</h2></div><p>The engine ranks requests using product availability, location, room context, queue age and colleague capacity. It can favour a fast floor pick, bundle a stockroom trip or offer an available alternative when a direct fulfilment path is less clear.</p><Link className="secondary-link" href="/demo/associate">View associate demo →</Link></section>
    <section className="platform-detail inverse" id="platform-3"><div><Eyebrow>Associate workflow</Eyebrow><h2>Actionable queues for a busy floor.</h2></div><p>Associates see the next task with its room, product, variant and route context. Managers see workload across teams and up to 32 rooms, supporting sensible reassignment without turning every request into an interruption.</p></section>
    <section className="platform-detail" id="platform-4"><div><Eyebrow>Analytics</Eyebrow><h2>Operational detail becomes a retail signal.</h2></div><p>FitOS brings together customer intent, queue performance, product availability and missed demand. The prototype uses local deterministic data to demonstrate these views; it does not claim conversion, savings or ROI outcomes.</p><Link className="secondary-link" href="/demo/manager">View manager demo →</Link></section>
    <section className="platform-detail inverse limitations" id="platform-5"><div><Eyebrow>Integrations & limitations</Eyebrow><h2>Built to test the experience before connecting systems.</h2></div><div className="detail-list"><span>Browser prototype only, with no production backend or authentication.</span><span>No payments, retailer integrations or inventory system connections are included.</span><span>Existing barcode labels are the primary identifier; RFID is optional.</span><span>Availability is represented as a stock confidence signal, not a guaranteed promise.</span></div></section>
    <section className="marketing-cta"><div><Eyebrow>Try the operating model</Eyebrow><h2>See FitOS across the fitting-room journey.</h2></div><Link className="button" href="/demo/manager">Open the live demo <span>→</span></Link></section>
  </SiteShell>;
}
