export function Polish() { return <style>{`
  :root{--ease:cubic-bezier(.2,.8,.2,1)}
  *{scroll-behavior:smooth} button,a,select,input{transition:transform .16s var(--ease),box-shadow .16s var(--ease),background-color .16s var(--ease),border-color .16s var(--ease),color .16s var(--ease)}
  button:hover:not(:disabled),a.button:hover{transform:translateY(-1px)} button:active:not(:disabled){transform:translateY(0) scale(.985)}
  :focus-visible{outline:3px solid #d2a44b;outline-offset:3px;border-radius:4px}.site-header{box-shadow:0 1px 0 #d9dfdc,0 8px 24px #15362b08}.site-header nav a{position:relative}.site-header nav a.active:after{content:"";position:absolute;height:2px;background:#284e46;left:0;right:0;bottom:-8px;border-radius:2px}
  .status{box-shadow:inset 0 0 0 1px #ffffff55}.status i{animation:statusPulse 2.6s ease-in-out infinite}.metric,.ops-metrics article,.manager-metric-grid article{transition:transform .2s var(--ease),box-shadow .2s var(--ease)}.metric:hover,.ops-metrics article:hover,.manager-metric-grid article:hover{transform:translateY(-2px);box-shadow:0 9px 18px #17342c0d}
  .request-card,.ops-queue article,.ranked-list article{animation:enterQueue .32s var(--ease) both}.request-card:nth-child(2),.ops-queue article:nth-child(2),.ranked-list article:nth-child(2){animation-delay:.04s}.request-card:nth-child(3),.ops-queue article:nth-child(3),.ranked-list article:nth-child(3){animation-delay:.08s}.room,.ops-room-grid button{transition:transform .17s var(--ease),box-shadow .17s var(--ease),background-color .24s var(--ease)}.room:hover,.ops-room-grid button:hover{transform:scale(1.045);z-index:2;box-shadow:0 4px 9px #17362b26}.customer-progress i.active{animation:progressIn .4s var(--ease)}.customer-confirm,.compare-note,.why-card,.shared-signal{animation:enterQueue .35s var(--ease)}
  .chart .bar,.hour-bars div{transform-origin:bottom;animation:barIn .5s var(--ease) both}.chart .bar:nth-child(2),.hour-bars div:nth-child(2){animation-delay:.05s}.chart .bar:nth-child(3),.hour-bars div:nth-child(3){animation-delay:.1s}.chart .bar:nth-child(4),.hour-bars div:nth-child(4){animation-delay:.15s}.chart .bar:nth-child(5),.hour-bars div:nth-child(5){animation-delay:.2s}.chart .bar:nth-child(6),.hour-bars div:nth-child(6){animation-delay:.25s}.chart .bar:nth-child(7),.hour-bars div:nth-child(7){animation-delay:.3s}
  .hero-panel,.intent-visual,.demo-stage,.metric-panel{background-image:radial-gradient(circle at 85% 12%,#ffffff12 0 1px,transparent 1px),radial-gradient(circle at 10% 90%,#ffffff0d 0 1px,transparent 1px);background-size:18px 18px,26px 26px}.empty-guidance{font-size:12px;color:#66716e;border:1px dashed #b7c5bd;border-radius:7px;padding:11px;background:#f7f9f6}
  @keyframes statusPulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.55;transform:scale(.78)}}@keyframes enterQueue{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}@keyframes progressIn{from{transform:scaleX(.3);opacity:.4}to{transform:scaleX(1);opacity:1}}@keyframes barIn{from{transform:scaleY(.15);opacity:.25}to{transform:scaleY(1);opacity:1}}
  @media(max-width:680px){main{padding-inline:18px}.site-header{padding-inline:18px}.site-header nav a.active:after{bottom:-4px}.scenario-control select{font-size:11px}.hero,.marketing-hero{min-height:auto}.manager-metric-grid article,.ops-metrics article{min-height:96px}}
  @media(min-width:1400px){main{max-width:1380px}.hero,.marketing-hero{padding-left:7vw;padding-right:7vw}.associate-ops,.manager-analytics,.pilot-story,.demo-controller{max-width:1280px}}
  @media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important;scroll-behavior:auto!important}}
`}</style>; }
