"""Better Auth's tables, owned by Alembic.

Revision ID: 0004
Revises: 0003

Better Auth ships a schema generator, and it would be reasonable to let it run
its own migrations. It is not what happens here: this repository has one
migration history, and two systems altering the same database on different
schedules is how a deployment ends up half-migrated with no single place to
look. So the schema is generated by
`npx @better-auth/cli generate --config apps/web/lib/auth.ts`, read, and
transcribed here — and `test_identity_schema.py` regenerates it and fails if
the two have drifted.

Three deliberate differences from the generated SQL:

- **ids are `uuid`, not `text`.** `memberships.user_id` is a uuid foreign key to
  `users.id`. Making the identity ids text would either break that reference or
  duplicate the user table, and a second answer to "who is this" is worse than
  a cast. `advanced.database.generateId` in the config emits UUIDs to match.
- **`display_name` stays nullable.** It already exists and already is; Better
  Auth wants NOT NULL, which is stricter than the data we may have.
- **no RLS.** These tables carry no `organization_id` — identity is not
  org-scoped, and a login has to work before an organization is chosen. What
  protects them is that the application role cannot read them at all.

That last point is the security decision worth stating plainly. `accounts` holds
password hashes and OAuth refresh tokens, and `jwks` holds the private signing
keys. `fitos_app` — the role every API request runs as — is granted nothing on
any of them. A SQL injection in the API therefore cannot reach the signing key,
because the role it runs as has no way to see the table.
"""

from __future__ import annotations

import os

import sqlalchemy as sa
from alembic import op
from fitos_api.tenancy_sql import APP_ROLE, AUTH_ROLE, create_auth_role
from sqlalchemy.dialects import postgresql

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None

IDENTITY_TABLES = ("sessions", "accounts", "verifications", "jwks")


def upgrade() -> None:
    # users already exists (0001). Expand it with the columns Better Auth needs.
    op.add_column(
        "users",
        sa.Column("email_verified", sa.Boolean, nullable=False, server_default=sa.false()),
    )
    op.add_column("users", sa.Column("image", sa.Text))
    op.add_column(
        "users",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )

    op.create_table(
        "sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token", sa.Text, nullable=False, unique=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.Text),
        sa.Column("user_agent", sa.Text),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("sessions_user_id_idx", "sessions", ["user_id"])

    op.create_table(
        "accounts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("account_id", sa.Text, nullable=False),
        sa.Column("provider_id", sa.Text, nullable=False),
        # Written by Better Auth at runtime but *absent* from the schema its own
        # CLI generates in this version. Found by running a sign-up against the
        # generated schema and getting `column "issuer" of relation "accounts"
        # does not exist`. Nullable rather than NOT NULL because the generator
        # disagrees with the runtime and the looser side is the safe one.
        sa.Column("issuer", sa.Text),
        sa.Column("access_token", sa.Text),
        sa.Column("refresh_token", sa.Text),
        sa.Column("id_token", sa.Text),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True)),
        sa.Column("refresh_token_expires_at", sa.DateTime(timezone=True)),
        sa.Column("scope", sa.Text),
        sa.Column("password", sa.Text),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("accounts_user_id_idx", "accounts", ["user_id"])

    op.create_table(
        "verifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("identifier", sa.Text, nullable=False),
        sa.Column("value", sa.Text, nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("verifications_identifier_idx", "verifications", ["identifier"])

    op.create_table(
        "jwks",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("public_key", sa.Text, nullable=False),
        sa.Column("private_key", sa.Text, nullable=False),
        sa.Column("alg", sa.Text),
        sa.Column("crv", sa.Text),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True)),
    )

    auth_password = os.environ.get("FITOS_AUTH_ROLE_PASSWORD")
    if not auth_password:
        raise RuntimeError(
            "FITOS_AUTH_ROLE_PASSWORD must be set to create the identity role. "
            "It is never defaulted: a default here becomes a production credential."
        )
    for statement in create_auth_role(auth_password):
        op.execute(statement)

    # The identity role owns identity, and only identity.
    op.execute(
        f"GRANT SELECT, INSERT, UPDATE, DELETE ON "
        f"{', '.join(IDENTITY_TABLES)}, users TO {AUTH_ROLE};"
    )

    # And the application role gets nothing on any of them. accounts holds
    # password hashes and refresh tokens; jwks holds the private signing keys.
    # An injection in the API cannot reach a key the role cannot see.
    op.execute(f"REVOKE ALL ON {', '.join(IDENTITY_TABLES)} FROM {APP_ROLE};")


def downgrade() -> None:
    raise NotImplementedError("roll forward with a new migration; see 0001")
